INSERT INTO equipment (equipment_name, description, img_src)
VALUES ('LEG PRESS HACK SQUAT MACHINE', 'The Leg Press Hack Squat Machine is the ultimate lower body strength training machine that combines leg press, hack squat, forward thrust, and calf raises.', 'https://www.titan.fitness/dw/image/v2/BDBZ_PRD/on/demandware.static/-/Sites-masterCatalog_Titan/default/dw47f28680/images/hi-res/Fitness/401486_01.jpg?sw=1001&sh=1000'),
('FUNCTIONAL TRAINER', 'Achieve a total body workout with the double stack Functional Trainer. Perform over 1,000 explosive, interactive strength training positions.', 'https://www.titan.fitness/dw/image/v2/BDBZ_PRD/on/demandware.static/-/Sites-masterCatalog_Titan/default/dw73026ce6/images/hi-res/Fitness/400883_01.jpg?sw=1001&sh=1000'),
('LAT TOWER ', 'Take your fitness workout to the next level with the tough and dependable Lat Tower.', 'https://www.titan.fitness/dw/image/v2/BDBZ_PRD/on/demandware.static/-/Sites-masterCatalog_Titan/default/dwa129300b/images/hi-res/Fitness/400467_01.jpg?sw=1001&sh=1000'),
('TITAN SERIES POWER RACK', 'Customize your TITAN Series Power Rack with your choice in custom color options, 90 or 100-inch uprights, 36 or 42-inch depth side bracings, and J-Hook Style.', 'https://www.titan.fitness/dw/image/v2/BDBZ_PRD/on/demandware.static/-/Sites-masterCatalog_Titan/default/dwd9332b28/images/hi-res/Fitness/401302_01.jpg?sw=1001&sh=1000'),
('PREACHER CURL STATION', 'The Preacher Curl Station will drastically improve your curling form, reduce elbow stress, and target your biceps.', 'https://www.titan.fitness/dw/image/v2/BDBZ_PRD/on/demandware.static/-/Sites-masterCatalog_Titan/default/dwc4eea763/images/hi-res/Fitness/401480_01.jpg?sw=1001&sh=1000'),
('WALL MOUNTED PULL-UP BAR', 'Mount the Ceiling Wall-Mount Pull-Up Bar at any width up to 52-inches with supplied 32 mm diameter bar.', 'https://www.titan.fitness/dw/image/v2/BDBZ_PRD/on/demandware.static/-/Sites-masterCatalog_Titan/default/dwa9833f31/images/hi-res/Fitness/400510_01.jpg?sw=1001&sh=1000'),
('T-3 SERIES YOKE', 'The yoke walk is a popular strongman event that has the athlete support a yoke, loaded with lots of weight, on his or her back, and then run with it for time.', 'https://www.titan.fitness/dw/image/v2/BDBZ_PRD/on/demandware.static/-/Sites-masterCatalog_Titan/default/dwa17989a9/images/hi-res/Fitness/400253_01.jpg?sw=1001&sh=1000'),
('KG CAST IRON KETTLEBELLS', 'Competition style Kettlebells.', 'https://www.titan.fitness/dw/image/v2/BDBZ_PRD/on/demandware.static/-/Sites-masterCatalog_Titan/default/dw8f87d9dc/images/hi-res/Fitness/KBCST_04.jpg?sw=1001&sh=1000');
